apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
        tier: backend
        track: stable
    spec:
      containers:
        - name: user
          image: "grajamca/user:1.0.0"
          ports:
            - name: user
              containerPort: 9112
          env:
            - name: USER_URL
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key:  customer_url
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
   customer_url: "http://localhost:9111/customer"
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
    tier: backend
  ports:
    - protocol: TCP
      port: 8112
      targetPort: user
  type: LoadBalancer